apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loadbalancer
  annotations:
    kubernetes.io/ingress.className: "traefik"
spec:
  defaultBackend:
    service:
      name: test
      port:
        number: 80
  rules:
    - host: app1.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app1
              port:
                number: 80
    - host: app2.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app2
              port:
                number: 80
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app3
              port:
                number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    app: app1
spec:
  ports:
  - port: 80
  selector:
    app: app1
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    app: app2
spec:
  ports:
  - port: 80
  selector:
    app: app2
---

apiVersion: v1
kind: Service
metadata:
  name: app3
  labels:
    app: app3
spec:
  ports:
  - port: 80
  selector:
    app: app3

---

# App1 deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: manmarti/iot:1.0
        env:
        - name: APP_NAME
          value: app1
        ports:
        - containerPort: 80

---

# App2 deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: manmarti/iot:1.0
        env:
        - name: APP_NAME
          value: app2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

# App3 deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: manmarti/iot:1.0
        env:
        - name: APP_NAME
          value: app3
        ports:
        - containerPort: 80
