Vagrant.configure(2) do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.synced_folder "./config", "/vagrant_shared"
    config.vm.define "josuna-tS" do |server|
        server.vm.hostname = "josuna-tS"
        server.vm.network :private_network, ip: "192.168.56.110"
        server.vm.network "forwarded_port", guest: 80, host: 80
        server.vm.provider "virtualbox" do |v|
            v.name = "josuna-tS"
            v.memory = 1024
            v.cpus = 1
        end
        server.vm.provision "shell",
        inline: "export K3S_TOKEN=1234; wget -qO- https://get.k3s.io | INSTALL_K3S_EXEC=--flannel-iface=eth1 sh - ;"
    end
end