Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "manmartiS" do |controller|
    controller.vm.hostname = "manmartiS"
    controller.vm.network "private_network", ip: "192.168.56.110"
    controller.vm.network "forwarded_port", guest: 80, host: 80
    controller.vm.provider "virtualbox" do |vb|
      vb.name = "manmartiS"
      vb.memory = "1024"
      vb.cpus   = "2"
    end

    controller.vm.provision "file", source: "./confs/p2.yml", destination: "p2.yml"
  
    controller.vm.provision :shell, inline:<<-SHELL
      wget -qO- https://get.k3s.io | INSTALL_K3S_EXEC='--flannel-iface=eth1' sh -;
      kubectl apply -f p2.yml;
    SHELL
  end

end