Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "manmartiS" do |controller|
    controller.vm.hostname = "manmartiS"
    controller.vm.network "private_network", ip: "192.168.56.110"
    
    controller.vm.provider "virtualbox" do |vb|
      vb.name = "manmartiS"
      vb.memory = "1024"
      vb.cpus   = "2"
    end

    controller.vm.provision :shell, inline:<<-SHELL
      wget -qO- https://get.k3s.io | K3S_TOKEN=testtoken INSTALL_K3S_EXEC='--flannel-iface=eth1' sh -
    SHELL
  end

  config.vm.define "manmartiSW" do |agent|
    agent.vm.hostname = "manmartiSW"
    agent.vm.network "private_network", ip: "192.168.56.111"

    agent.vm.provider "virtualbox" do |vb|
      vb.name = "manmartiSW"
      vb.memory = "1024"
      vb.cpus   = "2"
    end

    agent.vm.provision :shell, inline:<<-SHELL
      wget -qO- https://get.k3s.io | K3S_TOKEN=testtoken INSTALL_K3S_EXEC='--flannel-iface=eth1' K3S_URL=https://192.168.56.110:6443 sh -
    SHELL

  end

end