apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot
spec:
  destination:
    name: ""
    namespace: dev
    server: "https://kubernetes.default.svc"
  source:
    path: app
    repoURL: "https://github.com/Manmartin/manmarti.git"
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
