Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  
  config.vm.define "manmartiS" do |host|
    host.vm.hostname = "manmartiS"
    host.vm.network "private_network", ip: "192.168.56.110"
    host.vm.network "forwarded_port", guest: 8080, host: 8080
    host.vm.network "forwarded_port", guest: 8888, host: 8888
    host.vm.provider "virtualbox" do |vb|
      vb.name = "manmartiS"
      vb.memory = "2048"
      vb.cpus   = "2"
    end

    host.vm.provision "file", source: "./scripts/k3d.sh", destination: "k3d.sh"
    host.vm.provision "file", source: "./conf/ingress.yml", destination: "ingress.yml"
    host.vm.provision "file", source: "./conf/app.yml", destination: "app.yml"

    host.vm.provision :shell, inline:<<-SHELL
    chmod +x k3d.sh
    ./k3d.sh
    SHELL
  end

end
