Vagrant.configure(2) do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.synced_folder "./config", "/vagrant_shared"
    config.vm.define "josuna-tS" do |server|
        server.vm.hostname = "josuna-tS"
        server.vm.network :private_network, ip: "192.168.56.110"
        server.vm.network "forwarded_port", guest: 6443, host: 6443
        server.vm.provider "virtualbox" do |v|
            v.name = "josuna-tS"
            v.memory = 1024
            v.cpus = 1
        end
        server.vm.provision "shell", path: "scripts/script.sh"
    end
end